### ISSUE TITLE
Protected function?

### ISSUE THREAD

**Issue by richyvee** [rljohn/kuinameplates-target-helper#5] opened 2022-11-16 09:17 UTC
Ok I have no idea how this happend or what caused it or WHATEVER. I was taking the portal from Oribos to stormwind for the new prepatch quest.

I pressed my disengage mousebind, to move faster, got error sound from Bugsack/Grabber

"the message "KuiNameplatesTargetHelper has been blocked form an action only available to the BlizzUI, you can disable and reload"
popped up on my screen.

When I click disengage on my bars, i can disengage but when i use the mousebind i get the "protected funcrion dialogue".

and this lua error is what i am left with.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON12"]:2: in function <[string "MULTIACTIONBAR1BUTTON12"]:1>

**Comment by richyvee** [comment] 2022-11-16 09:17
Ok update. i get the dialogue when pressing any button now.

**Comment by Grimhead** [comment] 2022-11-19 09:29
Same problem :(

**Comment by rljohn** [comment] 2022-11-19 15:31
I will look into this. Nothing the addon does interacts with secure frames so there must be some sort of UI taint happening.

**Comment by Grimhead** [comment] 2022-11-19 15:59
````Some errors, it show up in 10.0.2, ealier all was OK:

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'ActionButton9:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:410: in function <FrameXML/ActionButton.lua:373>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:795: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>
```

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'ActionButton10:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:410: in function <FrameXML/ActionButton.lua:373>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:795: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>
```

**Comment by Grimhead** [comment] 2022-11-19 16:06
In 10.0.0 was OK, the errors start to show up in 10.0.2

**Comment by rljohn** [comment] 2022-11-19 19:43
Can you please check:
a) Can you reproduce this issue with all other addons disabled?
b) Provide a list of addons you're currently using?

I am unable to reproduce this.

**Comment by richyvee** [comment] 2022-11-19 20:05
Hey,
so for the easy stuff:
![image](https://user-images.githubusercontent.com/83710601/202869255-cf804bb9-5762-4776-b285-0c0c4b423219.png)
![image](https://user-images.githubusercontent.com/83710601/202869343-1380e0dd-a001-4719-a8ff-a45bd3c5f604.png)
![image](https://user-images.githubusercontent.com/83710601/202869350-8f5f8ccb-6013-42bf-a5bc-6b1a955b5671.png)
![image](https://user-images.githubusercontent.com/83710601/202869356-94d11fab-1c2e-4720-bf1d-0fad857eb065.png)
![image](https://user-images.githubusercontent.com/83710601/202869360-d79245cb-83e8-47f5-b53f-041b3c30a1ce.png)

that is pretty much how I have my addons setup currently, of course when the bug happened i had KUI Nameplates Target Helper activated aswell, but i deactivated it afterwards.

I'm activating the addon again now and see if it happens again and I will report to you if it happens again.

**Comment by richyvee** [comment] 2022-11-19 20:16
ok it happened again, I reactivated the addon, idlled a bit in oribos, then i took the portal to stormwind and pressed my disengage mouse keybind.
trying to repliacte it on video now.

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON12"]:2: in function <[string "MULTIACTIONBAR1BUTTON12"]:1>

**Comment by richyvee** [comment] 2022-11-19 20:34
sorry to clutter the thread:
cant seem to replicate it now, have to go to bed tho. I will have more time to look into it on sunday/monday.
take care

**Comment by richyvee** [comment] 2022-11-20 19:56
I dont know if this is the same issue, or a seperate one, but i have just entered karazahn zone throug the portal, mounted

flew to the entrance of kara

and got in combat with one of the flying mobs there

as soon as i entered combat i got "fatality" from bugsack/grabber
and this error message:
1x [ADDON_ACTION_BLOCKED] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'MultiBar6Button5:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:410: in function `Update'
[string "@FrameXML/ActionButton.lua"]:884: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:264: in function <FrameXML/ActionButton.lua:256>

have video footage of that if you want. same addons as above, will try to replicate with all addons turn off

**Comment by Grimhead** [comment] 2022-11-20 20:23
If you join party, then enter a m+ and try to use some consumable from bag, you will get error as below.
/reload helps, then all works well.

```
3x [ADDON_ACTION_FORBIDDEN] AddOn 'Kui_Nameplates_TargetHelper' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
```

**Comment by rljohn** [comment] 2022-11-20 20:31
I've found a reproduction from switching talent specializations.

I'll see what I can do to fix this tonight. I'm in the process of moving to a new computer so might see some delay. Thank you for your reports.

**Comment by rljohn** [comment] 2022-11-20 20:45
I think I found the error!

**Comment by richyvee** [comment] 2022-11-20 20:49
> I've found a reproduction from switching talent specializations and accessing edit mode.
> 
> I'll see what I can do to fix this tonight. I'm in the process of moving to a new computer so might see some delay. Thank you for your reports.


happy to help! I'lll keep it coming if i get new stuff

> I think I found the error!

NEAT!

**Comment by rljohn** [comment] 2022-11-21 00:13
Does the new version fix your issue?

**Comment by Grimhead** [comment] 2022-11-21 08:09
So far looks greate, thx :)

**Comment by richyvee** [comment] 2022-11-21 09:08
I've updated to the newest version just now, 
I should have time to play arround with it later today or tomorrow. If something happens I'll post it!

**Comment by richyvee** [comment] 2022-11-21 09:09
![image](https://user-images.githubusercontent.com/83710601/203010299-5812c159-2e94-4ff6-89bd-cc30602ed5f4.png)
sorry for that. My curiosity got the better of me.

**Comment by rljohn** [comment] 2022-11-22 02:58
Marking as fixed, re-open if this pops up again.

**Closed by rljohn** 2022-11-22 02:58 UTC
